//! Live coverage for the Phase 2 catalogue queries that the table scenario never reaches:
//! views, materialised views, routines, sequences, and the foreign-key, unique and check branches
//! of `constraints`. Those are exactly the paths whose type mappings only a real server exercises.
//!
//! Ignored by default, like the rest of the live tests. Every object is created inside a schema of
//! this test's own and dropped again at the end, so the database is left as it was found.

use rusty_sql_tool::database::{DatabaseObject, DatabaseProvider, ObjectKind};
use rusty_sql_tool::definition::{ColumnGeneration, ObjectDefinition};
use rusty_sql_tool::postgres::PostgresProvider;

const SCHEMA: &str = "rusty_sql_phase_two";

fn object(name: &str, kind: ObjectKind) -> DatabaseObject {
    DatabaseObject {
        schema: SCHEMA.into(),
        name: name.into(),
        kind,
    }
}

/// FR2-002, FR2-004, FR2-005, FR2-008 and PRD §14's view half, against a real server.
#[tokio::test]
#[ignore = "requires RUSTY_SQL_TEST_DATABASE_URL and a live PostgreSQL server"]
async fn every_object_kind_reports_its_definition() {
    let database_url = std::env::var("RUSTY_SQL_TEST_DATABASE_URL")
        .expect("RUSTY_SQL_TEST_DATABASE_URL must be set for the live smoke test");
    let profile = rusty_sql_tool::config::ConnectionProfile::from_database_url(&database_url)
        .expect("test database URL should be valid");
    let provider = PostgresProvider::new();
    provider.connect(&profile).await.expect("connect");

    provider
        .execute(&format!("DROP SCHEMA IF EXISTS {SCHEMA} CASCADE"))
        .await
        .expect("drop any leftovers");
    provider
        .execute(&format!("CREATE SCHEMA {SCHEMA}"))
        .await
        .expect("create schema");

    for statement in setup_statements() {
        provider
            .execute(&statement)
            .await
            .unwrap_or_else(|error| panic!("setup failed for {statement}: {error}"));
    }

    check_table(&provider).await;
    check_identity_and_generated_columns(&provider).await;
    check_view(&provider).await;
    check_materialised_view(&provider).await;
    check_function(&provider).await;
    check_procedure(&provider).await;
    check_sequences(&provider).await;
    check_dropped_table(&provider).await;

    provider
        .execute(&format!("DROP SCHEMA {SCHEMA} CASCADE"))
        .await
        .expect("clean up");
    provider.disconnect().await.expect("disconnect");
}

fn setup_statements() -> Vec<String> {
    vec![
        format!("CREATE TABLE {SCHEMA}.region (id bigint PRIMARY KEY, name text NOT NULL)"),
        format!(
            "CREATE TABLE {SCHEMA}.customer (\
               id bigint PRIMARY KEY, \
               region_id bigint NOT NULL REFERENCES {SCHEMA}.region (id), \
               email varchar(320) NOT NULL UNIQUE, \
               balance numeric NOT NULL DEFAULT 0 CHECK (balance >= 0))"
        ),
        format!(
            "CREATE TABLE {SCHEMA}.invoice (\
               id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY, \
               reference integer GENERATED BY DEFAULT AS IDENTITY, \
               price numeric NOT NULL, \
               quantity integer NOT NULL, \
               total numeric GENERATED ALWAYS AS (price * quantity) STORED, \
               légende text)"
        ),
        format!("CREATE VIEW {SCHEMA}.active_customer AS SELECT id, email FROM {SCHEMA}.customer"),
        format!(
            "CREATE MATERIALIZED VIEW {SCHEMA}.customer_total AS \
             SELECT region_id, count(*) AS customers FROM {SCHEMA}.customer GROUP BY region_id"
        ),
        format!(
            "CREATE FUNCTION {SCHEMA}.busiest_region(minimum integer) RETURNS bigint \
             LANGUAGE plpgsql AS $$ \
             BEGIN RETURN (SELECT region_id FROM {SCHEMA}.customer_total \
                            WHERE customers >= minimum LIMIT 1); END $$"
        ),
        format!(
            "CREATE PROCEDURE {SCHEMA}.tidy(older_than integer) LANGUAGE plpgsql AS $$ \
             BEGIN DELETE FROM {SCHEMA}.customer WHERE id < older_than; END $$"
        ),
        format!("CREATE SEQUENCE {SCHEMA}.unowned_seq START 5 INCREMENT 2 MAXVALUE 99 CYCLE"),
        format!("CREATE TABLE {SCHEMA}.legacy (id serial PRIMARY KEY)"),
    ]
}

/// FR2-002: the `'f'`, `'u'` and `'c'` branches of `constraints`, none of which the table scenario
/// in `postgres_smoke.rs` reaches.
async fn check_table(provider: &PostgresProvider) {
    let ObjectDefinition::Table(table) = provider
        .definition(&object("customer", ObjectKind::Table), true)
        .await
        .expect("customer definition")
    else {
        panic!("expected a table definition");
    };

    let primary = table
        .primary_key
        .clone()
        .expect("customer has a primary key");
    assert_eq!(primary.columns, vec!["id".to_owned()]);

    assert_eq!(table.foreign_keys.len(), 1, "{:?}", table.foreign_keys);
    let foreign = &table.foreign_keys[0];
    assert_eq!(foreign.columns, vec!["region_id".to_owned()]);
    assert_eq!(foreign.referenced_schema, SCHEMA);
    assert_eq!(foreign.referenced_table, "region");
    assert_eq!(foreign.referenced_columns, vec!["id".to_owned()]);

    assert_eq!(
        table
            .unique_constraints
            .iter()
            .map(|key| key.columns.clone())
            .collect::<Vec<_>>(),
        vec![vec!["email".to_owned()]]
    );

    assert_eq!(table.check_constraints.len(), 1);
    assert!(
        table.check_constraints[0].expression.starts_with("CHECK ("),
        "pg_get_constraintdef output should arrive unchanged: {}",
        table.check_constraints[0].expression
    );

    // §6: the referenced table is in the same schema, so the line is unqualified.
    let lines = rows_section(
        &ObjectDefinition::Table(table),
        &object("customer", ObjectKind::Table),
        "Foreign Keys",
    );
    assert!(
        lines[0].contains("→ region (id)"),
        "same-schema references are unqualified: {lines:?}"
    );
}

/// FR2-001: identity and generated columns are stated as what they are, not as defaults.
async fn check_identity_and_generated_columns(provider: &PostgresProvider) {
    let ObjectDefinition::Table(table) = provider
        .definition(&object("invoice", ObjectKind::Table), true)
        .await
        .expect("invoice definition")
    else {
        panic!("expected a table definition");
    };

    let by_name = |name: &str| {
        table
            .columns
            .iter()
            .find(|column| column.name == name)
            .unwrap_or_else(|| panic!("invoice should have a {name} column"))
            .clone()
    };

    assert_eq!(by_name("id").generation, ColumnGeneration::IdentityAlways);
    assert_eq!(by_name("id").default, None);
    assert_eq!(
        by_name("reference").generation,
        ColumnGeneration::IdentityByDefault
    );
    assert_eq!(by_name("total").generation, ColumnGeneration::Stored);
    assert!(
        by_name("total")
            .default
            .as_deref()
            .is_some_and(|expression| expression.contains("price")),
        "the generation expression should come through: {:?}",
        by_name("total").default
    );
    assert_eq!(by_name("légende").generation, ColumnGeneration::None);

    let lines = rows_section(
        &ObjectDefinition::Table(table),
        &object("invoice", ObjectKind::Table),
        "Columns",
    );
    assert!(
        lines
            .iter()
            .any(|line| line.contains("GENERATED ALWAYS AS IDENTITY")),
        "{lines:?}"
    );
    assert!(
        lines
            .iter()
            .any(|line| line.contains("GENERATED BY DEFAULT AS IDENTITY")),
        "{lines:?}"
    );
    assert!(
        lines
            .iter()
            .any(|line| line.contains("GENERATED ALWAYS AS (price") && line.ends_with("STORED")),
        "pg_get_expr already parenthesises the expression, so the clause needs no extra brackets: \
         {lines:?}"
    );
    // The accented identifier is padded by characters, not bytes, so the type column still lines
    // up with the rows above it.
    assert!(
        lines.iter().any(|line| line == "légende    text"),
        "{lines:?}"
    );
    assert!(
        !lines.iter().any(|line| line.contains("DEFAULT nextval")),
        "an identity column must not be reported as a nextval default: {lines:?}"
    );
}

/// FR2-004 and the view half of the §14 acceptance scenario.
async fn check_view(provider: &PostgresProvider) {
    let ObjectDefinition::View(view) = provider
        .definition(&object("active_customer", ObjectKind::View), true)
        .await
        .expect("view definition")
    else {
        panic!("expected a view definition");
    };

    assert!(!view.materialised);
    assert_eq!(
        view.columns
            .iter()
            .map(|column| column.name.as_str())
            .collect::<Vec<_>>(),
        vec!["id", "email"]
    );
    assert!(
        view.definition_sql.to_uppercase().contains("SELECT"),
        "pg_get_viewdef should return the query: {}",
        view.definition_sql
    );
}

/// §5: a materialised view stores rows, so it must not render identically to a view.
async fn check_materialised_view(provider: &PostgresProvider) {
    let definition = provider
        .definition(
            &object("customer_total", ObjectKind::MaterialisedView),
            true,
        )
        .await
        .expect("materialised view definition");
    let ObjectDefinition::View(view) = &definition else {
        panic!("expected a view definition");
    };

    assert!(view.materialised);
    assert!(view.definition_sql.contains("count"));

    let sections = definition.sections(&object("customer_total", ObjectKind::MaterialisedView));
    assert!(
        format!("{sections:?}").contains("Materialised view"),
        "{sections:?}"
    );
}

/// FR2-005: a function's arguments, return type, language and body. `pg_get_function_result`
/// arrives as a nullable column, so this is where that mapping is proved.
async fn check_function(provider: &PostgresProvider) {
    let ObjectDefinition::Routine(routine) = provider
        .definition(&object("busiest_region", ObjectKind::Function), true)
        .await
        .expect("function definition")
    else {
        panic!("expected a routine definition");
    };

    assert_eq!(routine.arguments, "minimum integer");
    assert_eq!(routine.return_type.as_deref(), Some("bigint"));
    assert_eq!(routine.language, "plpgsql");
    assert!(
        routine
            .definition_sql
            .contains("CREATE OR REPLACE FUNCTION"),
        "pg_get_functiondef should return the whole statement: {}",
        routine.definition_sql
    );
}

/// FR2-005: a procedure returns nothing, so the return type is absent rather than blank — the
/// `NULL` half of the `pg_get_function_result` mapping.
async fn check_procedure(provider: &PostgresProvider) {
    let ObjectDefinition::Routine(routine) = provider
        .definition(&object("tidy", ObjectKind::Procedure), true)
        .await
        .expect("procedure definition")
    else {
        panic!("expected a routine definition");
    };

    // A procedure's arguments carry their mode, which a function's do not. Both come from
    // `pg_get_function_arguments` verbatim (§7).
    assert_eq!(routine.arguments, "IN older_than integer");
    assert_eq!(routine.return_type, None);
    assert_eq!(routine.language, "plpgsql");
    assert!(routine.definition_sql.contains("PROCEDURE"));
}

/// FR2-008. Three sequences: one standalone, one behind `serial`, one behind an identity column.
/// Identity records an internal dependency rather than an auto one, so a query restricted to
/// `deptype = 'a'` would report an identity sequence as unowned.
async fn check_sequences(provider: &PostgresProvider) {
    let ObjectDefinition::Sequence(unowned) = provider
        .definition(&object("unowned_seq", ObjectKind::Sequence), true)
        .await
        .expect("sequence definition")
    else {
        panic!("expected a sequence definition");
    };
    assert_eq!(unowned.data_type, "bigint");
    assert_eq!(unowned.start, 5);
    assert_eq!(unowned.increment, 2);
    assert_eq!(unowned.maximum, 99);
    assert!(unowned.cycles);
    assert_eq!(unowned.owned_by, None);

    let ObjectDefinition::Sequence(serial) = provider
        .definition(&object("legacy_id_seq", ObjectKind::Sequence), true)
        .await
        .expect("serial sequence definition")
    else {
        panic!("expected a sequence definition");
    };
    assert_eq!(
        serial.owned_by.as_deref(),
        Some(format!("{SCHEMA}.legacy.id").as_str())
    );

    let ObjectDefinition::Sequence(identity) = provider
        .definition(&object("invoice_id_seq", ObjectKind::Sequence), true)
        .await
        .expect("identity sequence definition")
    else {
        panic!("expected a sequence definition");
    };
    assert_eq!(
        identity.owned_by.as_deref(),
        Some(format!("{SCHEMA}.invoice.id").as_str()),
        "an identity sequence is owned by the column it backs"
    );
}

/// §12: the case the tree makes easy to hit. All three table queries return nothing for a table
/// that has been dropped, which must read as an error rather than as a table with no columns.
async fn check_dropped_table(provider: &PostgresProvider) {
    let error = provider
        .definition(&object("no_such_table", ObjectKind::Table), true)
        .await
        .expect_err("a missing table must not report an empty definition");

    assert_eq!(error.message, "the object no longer exists");
}

fn rows_section(
    definition: &ObjectDefinition,
    object: &DatabaseObject,
    heading: &str,
) -> Vec<String> {
    definition
        .sections(object)
        .into_iter()
        .find_map(|section| match section {
            rusty_sql_tool::definition::DefinitionSection::Rows {
                heading: found,
                lines,
            } if found == heading => Some(lines),
            _ => None,
        })
        .unwrap_or_else(|| panic!("expected a {heading} section"))
}
